[2016-01-27 00:45:03,980 #126 INFO] Reading the site collection
[2016-01-27 00:45:04,052 #126 INFO] Reading the composite source model
[2016-01-27 00:45:04,066 #126 CRITICAL] 
Traceback (most recent call last):
  File "/home/nick/src/python/GEM/oq-risklib/openquake/calculators/base.py", line 128, in run
    self.pre_execute()
  File "/home/nick/src/python/GEM/oq-risklib/openquake/calculators/base.py", line 304, in pre_execute
    self.oqparam)
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/readinput.py", line 495, in get_composite_source_model
    oqparam, source_model_lt, in_memory=in_memory):
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/readinput.py", line 440, in get_source_models
    fname, converter, apply_unc, set_weight=in_memory)
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/source.py", line 213, in parse_source_model
    for no, src_node in enumerate(src_nodes, 1):
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/node.py", line 530, in read_nodes
    raise_(etype, msg, tb)
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/node.py", line 521, in read_nodes
    for _, el in iterparse(fname, remove_comments=remove_comments):
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/node.py", line 177, in iterparse
    return ElementTree.iterparse(source, events, SourceLineParser(), **kw)
  File "/usr/local/src/python/anaconda3/envs/py27/lib/python2.7/xml/etree/ElementTree.py", line 1199, in iterparse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: u'/home/nick/Desktop/Individual Study/Jobs/smoothed_only/nath2012probabilistic_smoothed_source_model_mmin4.5'
[2016-01-27 00:45:04,166 #126 CRITICAL] Traceback (most recent call last):
  File "/home/nick/src/python/GEM/oq-engine/openquake/engine/engine.py", line 222, in run_calc
    _do_run_calc(calculator, exports, hazard_calculation_id)
  File "/home/nick/src/python/GEM/oq-engine/openquake/engine/engine.py", line 240, in _do_run_calc
    calc.run(exports=exports, hazard_calculation_id=hazard_calculation_id)
  File "/home/nick/src/python/GEM/oq-risklib/openquake/calculators/base.py", line 128, in run
    self.pre_execute()
  File "/home/nick/src/python/GEM/oq-risklib/openquake/calculators/base.py", line 304, in pre_execute
    self.oqparam)
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/readinput.py", line 495, in get_composite_source_model
    oqparam, source_model_lt, in_memory=in_memory):
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/readinput.py", line 440, in get_source_models
    fname, converter, apply_unc, set_weight=in_memory)
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/source.py", line 213, in parse_source_model
    for no, src_node in enumerate(src_nodes, 1):
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/node.py", line 530, in read_nodes
    raise_(etype, msg, tb)
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/node.py", line 521, in read_nodes
    for _, el in iterparse(fname, remove_comments=remove_comments):
  File "/home/nick/src/python/GEM/oq-risklib/openquake/commonlib/node.py", line 177, in iterparse
    return ElementTree.iterparse(source, events, SourceLineParser(), **kw)
  File "/usr/local/src/python/anaconda3/envs/py27/lib/python2.7/xml/etree/ElementTree.py", line 1199, in iterparse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: u'/home/nick/Desktop/Individual Study/Jobs/smoothed_only/nath2012probabilistic_smoothed_source_model_mmin4.5'

